
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  pathToP2: NotFightClub/
  pathToP2Sln: $(pathToP2)/NotFightClub.sln

trigger:

- main
- testbranch

pool:
  vmImage: ubuntu-latest

steps: 

  - task: UseDotNet@2
    displayName: dotnet sdk
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '2.x'


