
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  pathToP2: NotFightClub/
  pathToP2Sln: $(pathToP2)/NotFightClub.sln
  p2PackagePath: $(Build.ArtifactStagingDirectory)

trigger:

- main
- testbranch

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: buildJob
    steps:
    - task: UseDotNet@2
      inputs:
        version: '5.0.x'
   # - task: DownloadSecureFile@1
    #  name: PubXML
     # displayName: 'Download .pubxml for Deployment'
      #inputs:
       # secureFile: 'NotFightClub-P2.pubxml'
    - task: VSBuild@1
      inputs:
        solution: '$(pathToP2Sln)'
        msbuildArgs: '/t:Restore;Build'


