
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  pathToP2: NotFightClub/
  pathToP2Sln: $(pathToP2)/NotFightClub.sln
  p2PackagePath: $(Build.ArtifactStagingDirectory)
  pathTop2Ang:  $(pathToP2)/Angular

trigger:

- main
- testbranch

pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: buildJob
    steps:
    - task: UseDotNet@2
      inputs:
        version: '5.0.x'
  


    - task: VSBuild@1
      inputs:
        solution: '$(pathToP2Sln)'
        msbuildArgs: '/t:Restore;Build'
      
- stage: Publish
  jobs:
  - job: publishapi
    steps:
      - task: DotNetCoreCLI@2
        displayName: Publishing
        inputs:
          command: 'publish'
          publishWebProjects: true
          projects: $(pathtosolution)
          zipAfterPublish: true
      - task: AzureRmWebAppDeployment@4
        displayName: Deployment
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'NotFightClub(8f7a3d65-6e62-4cf4-b5a9-193406d2e5c2)'
          WebAppName: 'NotFightClubApi'
          packageForLinux: $(System.DefaultWorkingDirectory)/**/*.zip'
